import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CenterThumbnail from "../components/CenterThumbnail";
import Link from "next/link";
export default function Home({ categories }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.header_text}>Choose Category</h1>
      <div className={styles.thumbnail_container}>
        {categories?.trivia_categories.map((category) => (
          <Link href={`/quiz?category=${category.id}`}>
            <a className={styles.thumbnail_link}>
              <CenterThumbnail>
                <p>{category.name}</p>
              </CenterThumbnail>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
}
export async function getStaticProps() {
  const res = await fetch("https://opentdb.com/api_category.php");
  const data = await res.json();
  return {
    props: {
      categories: data,
    },
  };
}
